# Cloudflare Pages Configuration for Hexo Blog

name = "ggggoods-hexo"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "source"

[build.environment_variables]
NODE_VERSION = "18"

[[build.upload]]
format = "directory"
dir = "public"
